### PR TITLE
fix/directories - Avoid parsing directories

### LINKED ISSUE #12: [BUG] Parser incorrectly assumes anything ending in .js,.jsx or .tsx is a file
**Describe the bug**
Parser naively uses glob pattern `/**/*.{js,jsx,tsx}` to find files.
This will fail if a directory ends in .js, .jsx or .tsx.

**To Reproduce**
1. Create new directory named test.js
2. Run `react-bratus -s`

**Expected behavior**
Correctly parses content

**Actual behaviour**
Throws error: `Error: EISDIR: illegal operation on a directory, read`

**Additional context**

### PR DESCRIPTION
**Pull request by johansundwall**
Closes #12

### CODE REVIEW

File: packages/parser/src/ASTParser.ts [hunk 1]
```diff
@@ -36,21 +36,23 @@ class ASTParser {
...
-                  `[Info] Adding component: ${componentName}`
-                );
-                this.componentMap.set(componentName, component);
-              } else {
-                ASTParser.logEntryToFile(
-                  `[Warning] A duplicate component found which was not added: ${componentName}`
-                );
-              }
-            });
+          if (fs.existsSync(files[i]) && fs.lstatSync(files[i]).isFile()) {
```
Comment (stephanboersma) [inline packages/parser/src/ASTParser.ts:39]: Great, thanks for spotting this issue :-)

**Review by stephanboersma — APPROVED** [review]
Thanks for your contribution!
